version: "3"

services:
  demo:
    image: demo:latest
    environment:
      APP_NAME: e_care_dev
      NAMESPACE: dev
      TZ: Asia/Shanghai
    volumes:
      - ./:/code
    ports:
      - "40039:8080"
    command: sh entrypoint.sh
    labels:
      - "SERVICE=ai_character"
      - "NAMESPACE=dev"
