from pydantic import BaseModel, Field

class User_info(BaseModel):
    name: str = Field("", description='User name')
    age: int = Field(0, description='User age')
    gender: str = Field("", description='User gender')
    address: str = Field("", description='address')
    nationality: str = Field("", description='User nationality')
    chronic_diseases: str = Field("", description='chronic diseases')
    acute_diseases: str = Field("", description='acute diseases')
    disability_status: str = Field("", description='whether disabled')
    mental_state: str = Field("", description='metal health')
    daily_routine: str = Field("", description='daily routine')
    diet: str = Field("", description='diet info')
    exercise: str = Field("", description='daily exercise')
    hobby: str =Field("", description='hobby')
    income: str = Field("", description='main source of income')
    consume_info: str = Field("", description='main comsumption')
    price_sensity: str = Field("", description='sensity to price')
    marital_status: str = Field("", description='marital status')
    children_situation: str = Field("", description='children situation')
    life_status: str = Field("", description='life status')
    other: str = Field("", description='other information')